blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/loopcraftlab/docqet/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/loopcraftlab/docqet/tree/main/docs
    about: Check our documentation for guides and tutorials.
