# Alertmanager Configuration for Docqet Infrastructure

global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pager-duty-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-notifications'
      continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#docqet-alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        title_link: '{{ template "slack.titlelink" . }}'
        footer: '{{ template "slack.footer" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.grafanaURL" . }}'
          - type: button
            text: 'View in Prometheus'
            url: '{{ template "slack.prometheusURL" . }}'

  - name: 'pager-duty-critical'
    pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_ROUTING_KEY'
        description: '{{ template "pagerduty.description" . }}'
        severity: '{{ if eq .CommonLabels.severity "critical" }}critical{{ else }}warning{{ end }}'
        client: 'Docqet Alertmanager'
        client_url: '{{ template "pagerduty.clientURL" . }}'

  - name: 'email-notifications'
    email_configs:
      - to: 'devops@docqet.com'
        from: 'alertmanager@docqet.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alertmanager@docqet.com'
        auth_password: 'YOUR_EMAIL_PASSWORD'
        headers:
          subject: 'Docqet Alert: {{ .GroupLabels.alertname }}'

templates:
  - '/etc/alertmanager/template/*.tmpl' 