name: Project Setup

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  setup-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup GitHub CLI
      uses: cli/setup-gh@v2
    
    - name: Setup repository
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Set repository description
        gh repo edit --description "Secure Document Sharing with AI - A modern, open-source document management platform with intelligent content analysis and real-time collaboration features."
        
        # Enable features
        gh repo edit --enable-issues --enable-wiki --enable-projects
        
        # Add topics
        gh repo edit --add-topic "document-management,ai,fastapi,nextjs,typescript,python,postgresql,redis,vector-search,open-source,security,collaboration"
    
    - name: Setup branch protection
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Enable branch protection for main branch
        gh api repos/loopcraftlab/docqet/branches/main/protection \
          --method PUT \
          --field required_status_checks='{"strict":true,"contexts":["quality-checks","test","security"]}' \
          --field enforce_admins=true \
          --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true}' \
          --field restrictions=null || echo "Branch protection setup failed or already configured" 